services:
  web:
    build: .
    ports:
      - "8080:80"
    # docker run -p 8080:80 nginx:latest
    develop:
      watch:
        - action: sync
          path: ./site
          target: /usr/share/nginx/html
        - action: rebuild
          path: package.json
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    # docker run -e POSTGRES_PASSWORD=example postgres:latest 
